[build]
target = "wasm32-unknown-unknown"


# Configuration specific to the wasm32-unknown-unknown target
[target.wasm32-unknown-unknown]
rustflags = [
    
    # size
    "-Zlocation-detail=none",
    "-Zfmt-debug=none",

    # may be required to target older wasm engines
    # "-Ctarget-cpu=mvp",

    "-Cpanic=abort",
]



[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["optimize_for_size", "panic_immediate_abort"]